/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.eattogo.client.presentation;

import co.unicauca.eattogo.client.access.FactoryPlate;
import co.unicauca.eattogo.client.access.IPlateAccess;
import co.unicauca.eattogo.client.domain.services.PlateService;
import static co.unicauca.eattogo.client.infra.Messages.successMessage;
import static co.unicauca.eattogo.client.infra.Messages.warningMessage;
import co.unicauca.eattogo.commons.domain.EnumCategory;
import co.unicauca.eattogo.commons.domain.Plate;
import java.awt.event.KeyEvent;

/**
 * Interfaz gráfica que permite al administrador agregar un nuevo plato especial
 * @author Personal
 */
public class GUIAddSpecialPlate extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIAddSpecialPlate
     */
    public GUIAddSpecialPlate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jtfNombrePlato = new javax.swing.JTextField();
        jtfDescripcionPlato = new javax.swing.JTextField();
        jtfPrecioPlato = new javax.swing.JTextField();
        jcbCategoriaPlato = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("*Nombre del Plato:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel2.setText("*Descripcion:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel3.setText("*Precio:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel4.setText("*Categoria:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 110, 30));

        jtfNombrePlato.setBorder(null);
        jPanel2.add(jtfNombrePlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 270, 30));

        jtfDescripcionPlato.setBorder(null);
        jPanel2.add(jtfDescripcionPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 270, 30));

        jtfPrecioPlato.setBorder(null);
        jtfPrecioPlato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfPrecioPlatoKeyTyped(evt);
            }
        });
        jPanel2.add(jtfPrecioPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 270, 30));

        jcbCategoriaPlato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una Opcion", "Pollo", "Carne", "Cerdo", "Vegetariano", "Pasta" }));
        jPanel2.add(jcbCategoriaPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 270, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 270, 20));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 270, 20));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 270, 20));

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel6.setText("Agregar un Plato");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 160, 30));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jPanel2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        IPlateAccess service = FactoryPlate.getInstance().getPlateService();
        // Inyecta la dependencia
        PlateService plateService = new PlateService(service);
        Plate plate = new Plate();
        
        if(jtfPrecioPlato.getText().isEmpty()){
            plate.setPrice(0);
        }else{
           plate.setPrice(Integer.parseInt(jtfPrecioPlato.getText())); 
        }
        
        if(jcbCategoriaPlato.getSelectedItem().toString().compareTo("Seleccione una Opcion") == 0){
            warningMessage("Debe seleccionar una categoria", "Atención");
            return;
        }else{
            plate.setCategory(EnumCategory.valueOf(jcbCategoriaPlato.getSelectedItem().toString()));
        }
          
        plate.setName(jtfNombrePlato.getText());
        plate.setDescription(jtfDescripcionPlato.getText());       
        
        
        try {           
            String response = plateService.createPlate(plate);
            successMessage("Plato "+ response + " agregado con éxito.", "Atención");
            clearControls();

        } catch (Exception ex) {
            warningMessage(ex.getMessage(), "Atención");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfPrecioPlatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPrecioPlatoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
          if (!((c >= '0') && (c <= '9') ||
             (c == KeyEvent.VK_BACK_SPACE) ||
             (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();}
    }//GEN-LAST:event_jtfPrecioPlatoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAddSpecialPlate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAddSpecialPlate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAddSpecialPlate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAddSpecialPlate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUIAddSpecialPlate special =  new GUIAddSpecialPlate();
                special.setVisible(true);
            }
        });
    }
    
    /**
     * Se encarga de liberar los textfields y el combobox.
     */
    public void clearControls() {
        jtfNombrePlato.setText("");
        jtfDescripcionPlato.setText("");
        jtfPrecioPlato.setText("");
        jcbCategoriaPlato.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> jcbCategoriaPlato;
    private javax.swing.JTextField jtfDescripcionPlato;
    private javax.swing.JTextField jtfNombrePlato;
    private javax.swing.JTextField jtfPrecioPlato;
    // End of variables declaration//GEN-END:variables
}
